modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_mod_roller_plough_fix"
version="1.0.9"
displayName="Create Mod Roller & Plough Fix"
logoFile="icon.png"
authors="DigitalDan68"
description='''
Allows Create's Mechanical Roller and Mechanical Plough to interact with the main world from Create Aeronautics simulated contraptions.
'''

[[mixins]]
config="create_mod_roller_plough_fix.mixins.json"

[[dependencies.create_mod_roller_plough_fix]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_mod_roller_plough_fix]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.create_mod_roller_plough_fix]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mod_roller_plough_fix]]
modId="sable"
type="required"
versionRange="[2.0.0,3.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mod_roller_plough_fix]]
modId="aeronautics"
type="required"
versionRange="[1.3.0,)"
ordering="AFTER"
side="BOTH"
